"""EPG stimulated-echo-corrected MWF — hermetic checks.

The EPG forward model is validated bit-exact against DECAES ``EPGdecaycurve``
out-of-band; here we pin the properties that don't need Julia:
  * ideal 180-deg refocusing reduces to a pure mono-exponential decay,
  * a regression value bit-exact to the DECAES reference (guards the recursion),
  * a sub-180 flip angle produces the even/odd echo oscillation it must model,
  * end-to-end MWF recovery on a synthetic two-pool signal.
"""

import numpy as np
import pytest

from neurofaune.preprocess.utils.epg_mwf import (
    epg_decay_curve,
    calculate_mwf_epg,
)


def test_ideal_refocusing_is_monoexponential():
    # At alpha = 180 deg (perfect refocusing) the CPMG echo train is a pure
    # exponential exp(-n*TE/T2); no stimulated echoes.
    ETL, TE, T2 = 32, 0.01, 0.055
    dc = epg_decay_curve(ETL, 180.0, TE, T2, T1=1.0)
    n = np.arange(1, ETL + 1)
    ideal = np.exp(-n * TE / T2)
    assert np.allclose(dc, ideal, atol=1e-6)


def test_regression_value_matches_decaes():
    # Bit-exact reference generated by DECAES.EPGdecaycurve(32, 150, 0.01, 0.015, 1.0, 180).
    dc = epg_decay_curve(32, 150.0, 0.01, 0.015, T1=1.0)
    ref_first4 = np.array([0.4627023228106838, 0.28301938084182593,
                           0.1128978316709988, 0.09028739766130736])
    assert np.allclose(dc[:4], ref_first4, atol=1e-10)


def test_sub180_flip_angle_oscillates():
    # A refocusing angle < 180 deg produces stimulated echoes -> even/odd
    # oscillation in the early echo-to-echo ratios (the artifact EPG models).
    dc = epg_decay_curve(32, 150.0, 0.01, 0.055, T1=1.0)
    ratios = dc[1:6] / dc[:5]
    # odd->even steps differ systematically from even->odd steps
    assert abs(np.mean(ratios[0::2]) - np.mean(ratios[1::2])) > 0.02


def test_synthetic_two_pool_mwf_recovery():
    # Build a 2-pool decay (myelin T2=15ms @ 15%, IEW T2=60ms @ 85%) through the
    # EPG model at alpha=150, then confirm the fit recovers MWF ~0.15 and the
    # flip angle ~150 deg.
    ETL, TE = 32, 0.01
    sig = (0.15 * epg_decay_curve(ETL, 150.0, TE, 0.015, T1=1.0)
           + 0.85 * epg_decay_curve(ETL, 150.0, TE, 0.060, T1=1.0))
    data = sig.reshape(1, 1, 1, ETL).astype(float)
    mask = np.ones((1, 1, 1), dtype=bool)
    te_ms = np.arange(1, ETL + 1) * (TE * 1000)
    mwf, iwf, csf, t2, alpha = calculate_mwf_epg(
        data, mask, te_ms, n_components=40, t2_range=[10, 2000],
        myelin_water_cutoff=25, intra_extra_cutoff=200, T1=1000.0,
        n_angles=12, n_workers=1)
    assert 0.08 < mwf[0, 0, 0] < 0.22        # recovers ~0.15
    assert 130 < alpha[0, 0, 0] < 170        # recovers ~150 deg
